//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveCursorByHand.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoveCursorByHand.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;haarcascade_hand type_id=&quot;opencv-haar-classifier&quot;&gt;
        ///  &lt;size&gt;
        ///    48 48&lt;/size&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;!-- stage 0 --&gt;
        ///      &lt;trees&gt;
        ///        &lt;_&gt;
        ///          &lt;!-- tree 0 --&gt;
        ///          &lt;_&gt;
        ///            &lt;!-- root node --&gt;
        ///            &lt;feature&gt;
        ///              &lt;rects&gt;
        ///                &lt;_&gt;
        ///                  19 19 3 4 -1.&lt;/_&gt;
        ///                &lt;_&gt;
        ///                  20 19 1 4 3.&lt;/_&gt;&lt;/rects&gt;
        ///              &lt;tilted&gt;0&lt;/tilted&gt;&lt;/feature&gt;
        ///            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1256617233_1_haarcascade_hand {
            get {
                return ResourceManager.GetString("_1256617233_1_haarcascade_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///--&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;A_gest type_id=&quot;opencv-haar-classifier&quot;&gt;
        ///  &lt;size&gt;
        ///    24 24&lt;/size&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;!-- stage 0 --&gt;
        ///      &lt;trees&gt;
        ///        &lt;_&gt;
        ///          &lt;!-- tree 0 --&gt;
        ///          &lt;_&gt;
        ///            &lt;!-- root node --&gt;
        ///            &lt;feature&gt;
        ///              &lt;rects&gt;
        ///                &lt;_&gt;
        ///                  3 3 9 16 -1.&lt;/_&gt;
        ///                &lt;_&gt;
        ///                  3 7 9 8 2.&lt;/_&gt;&lt;/rects&gt;
        ///              &lt;tilted&gt;0&lt;/tilted&gt;&lt;/feature&gt;
        ///            &lt;threshold&gt;-0.022344 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aGest {
            get {
                return ResourceManager.GetString("aGest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background2 {
            get {
                object obj = ResourceManager.GetObject("background2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background3 {
            get {
                object obj = ResourceManager.GetObject("background3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background4 {
            get {
                object obj = ResourceManager.GetObject("background4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backgroundPart1 {
            get {
                object obj = ResourceManager.GetObject("backgroundPart1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;cascade&gt;
        ///  &lt;stageType&gt;BOOST&lt;/stageType&gt;
        ///  &lt;featureType&gt;HAAR&lt;/featureType&gt;
        ///  &lt;height&gt;20&lt;/height&gt;
        ///  &lt;width&gt;20&lt;/width&gt;
        ///  &lt;stageParams&gt;
        ///    &lt;boostType&gt;GAB&lt;/boostType&gt;
        ///    &lt;minHitRate&gt;9.9500000476837158e-001&lt;/minHitRate&gt;
        ///    &lt;maxFalseAlarm&gt;5.0000000000000000e-001&lt;/maxFalseAlarm&gt;
        ///    &lt;weightTrimRate&gt;9.4999999999999996e-001&lt;/weightTrimRate&gt;
        ///    &lt;maxDepth&gt;1&lt;/maxDepth&gt;
        ///    &lt;maxWeakCount&gt;100&lt;/maxWeakCount&gt;&lt;/stageParams&gt;
        ///  &lt;featureParams&gt;
        ///    &lt;maxCatCount&gt;0&lt;/maxCatCount&gt;
        ///    &lt;fe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cascade {
            get {
                return ResourceManager.GetString("cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;A_gest type_id=&quot;opencv-haar-classifier&quot;&gt;
        ///  &lt;size&gt;
        ///    24 24&lt;/size&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;!-- stage 0 --&gt;
        ///      &lt;trees&gt;
        ///        &lt;_&gt;
        ///          &lt;!-- tree 0 --&gt;
        ///          &lt;_&gt;
        ///            &lt;!-- root node --&gt;
        ///            &lt;feature&gt;
        ///              &lt;rects&gt;
        ///                &lt;_&gt;
        ///                  3 3 9 16 -1.&lt;/_&gt;
        ///                &lt;_&gt;
        ///                  3 7 9 8 2.&lt;/_&gt;&lt;/rects&gt;
        ///              &lt;tilted&gt;0&lt;/tilted&gt;&lt;/feature&gt;
        ///            &lt;threshold&gt;-0.0223442204296589&lt;/threshold&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fist {
            get {
                return ResourceManager.GetString("fist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grayscale_hand {
            get {
                object obj = ResourceManager.GetObject("grayscale_hand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;A_gest type_id=&quot;opencv-haar-classifier&quot;&gt;
        ///  &lt;size&gt;
        ///    24 24&lt;/size&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;!-- stage 0 --&gt;
        ///      &lt;trees&gt;
        ///        &lt;_&gt;
        ///          &lt;!-- tree 0 --&gt;
        ///          &lt;_&gt;
        ///            &lt;!-- root node --&gt;
        ///            &lt;feature&gt;
        ///              &lt;rects&gt;
        ///                &lt;_&gt;
        ///                  3 3 9 16 -1.&lt;/_&gt;
        ///                &lt;_&gt;
        ///                  3 7 9 8 2.&lt;/_&gt;&lt;/rects&gt;
        ///              &lt;tilted&gt;0&lt;/tilted&gt;&lt;/feature&gt;
        ///            &lt;threshold&gt;-0.0223442204296589&lt;/threshold&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hand {
            get {
                return ResourceManager.GetString("hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;haarcascade_hand type_id=&quot;opencv-haar-classifier&quot;&gt;
        ///  &lt;size&gt;
        ///    48 48&lt;/size&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;!-- stage 0 --&gt;
        ///      &lt;trees&gt;
        ///        &lt;_&gt;
        ///          &lt;!-- tree 0 --&gt;
        ///          &lt;_&gt;
        ///            &lt;!-- root node --&gt;
        ///            &lt;feature&gt;
        ///              &lt;rects&gt;
        ///                &lt;_&gt;
        ///                  19 19 3 4 -1.&lt;/_&gt;
        ///                &lt;_&gt;
        ///                  20 19 1 4 3.&lt;/_&gt;&lt;/rects&gt;
        ///              &lt;tilted&gt;0&lt;/tilted&gt;&lt;/feature&gt;
        ///            &lt;threshold&gt;-1.0453 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hand_2 {
            get {
                return ResourceManager.GetString("hand_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;Hand_Dataset type_id=&quot;opencv-haar-classifier&quot;&gt;
        ///  &lt;size&gt;
        ///    25 25&lt;/size&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;!-- stage 0 --&gt;
        ///      &lt;trees&gt;
        ///        &lt;_&gt;
        ///          &lt;!-- tree 0 --&gt;
        ///          &lt;_&gt;
        ///            &lt;!-- root node --&gt;
        ///            &lt;feature&gt;
        ///              &lt;rects&gt;
        ///                &lt;_&gt;
        ///                  0 2 24 21 -1.&lt;/_&gt;
        ///                &lt;_&gt;
        ///                  6 2 12 21 2.&lt;/_&gt;&lt;/rects&gt;
        ///              &lt;tilted&gt;0&lt;/tilted&gt;&lt;/feature&gt;
        ///            &lt;threshold&gt;1.500305980 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hand_Cascade_1 {
            get {
                return ResourceManager.GetString("Hand_Cascade_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hand_overlay {
            get {
                object obj = ResourceManager.GetObject("hand_overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maximize {
            get {
                object obj = ResourceManager.GetObject("maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_signal {
            get {
                object obj = ResourceManager.GetObject("no_signal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap options_plate {
            get {
                object obj = ResourceManager.GetObject("options_plate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap optionsPlate2 {
            get {
                object obj = ResourceManager.GetObject("optionsPlate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap optionsPlate3 {
            get {
                object obj = ResourceManager.GetObject("optionsPlate3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;!-- Automatically converted from ./contract_palm4/haarcascade, window size = 20x20 --&gt;
        ///&lt;CP04_3 type_id=&quot;opencv-haar-classifier&quot;&gt;
        ///  &lt;size&gt;
        ///    20 20&lt;/size&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;!-- stage 0 --&gt;
        ///      &lt;trees&gt;
        ///        &lt;_&gt;
        ///          &lt;!-- tree 0 --&gt;
        ///          &lt;_&gt;
        ///            &lt;!-- root node --&gt;
        ///            &lt;feature&gt;
        ///              &lt;rects&gt;
        ///                &lt;_&gt;
        ///                  14 0 6 16 -1.&lt;/_&gt;
        ///                &lt;_&gt;
        ///                  17 0 3 16 2.&lt;/_&gt;&lt;/rec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string palm {
            get {
                return ResourceManager.GetString("palm", resourceCulture);
            }
        }
    }
}
